### PR TITLE
Issue #1: JMS Get started samples do not show how to set password

### PR DESCRIPTION
**Pull request by bczoma**
Updated source code for all samples and documentation for Publish/Subscribe (all the other docs reference to this one for this section).

### CODE REVIEW

**Comment by mdspielman** [comment]
The code changes look good. Can you please update the tutorial descriptions as well to outline password setting.

**Comment by bczoma** [comment]
There is already some info in the "Solace message router properties" section about username and password. 
Perhaps I could add to the "Connecting to the Solace message router" section that if using a non-default message vpn, usename or password the following code shows how to specify it ?

**Comment by bczoma** [comment]
I could also refer to the router docs on how to set up security.

**Comment by mdspielman** [comment]
My mistake, I missed your edit to the markdown. Looks good as updated.

**Pull request merged**
